# Generated by Django 4.0.2 on 2022-02-17 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/5ce4719f-6459-420d-84f2-64700a57991d')),
                ('phone', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='phone must be an egyptian phone number...', regex='^01[1|0|2|5][0-9]{8}$')], verbose_name='phone')),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('education_degree', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=50)),
                ('achievements', models.TextField(null=True)),
                ('status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('report', models.FileField(upload_to='uploads/% Y/% m/% d/')),
                ('phone', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='phone must be an egyptian phone number...', regex='^01[1|0|2|5][0-9]{8}$')], verbose_name='phone')),
                ('date_of_birth', models.DateField(null=True)),
                ('record_number', models.TextField()),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('guardian', models.CharField(max_length=20, null=True)),
                ('guardian_relation', models.CharField(choices=[('first degree', 'First Degree'), ('second degree', 'Second Degree')], max_length=30)),
            ],
        ),
    ]
