# Generated by Django 4.0.2 on 2022-02-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/4238bfc4-72c7-4380-aed2-d3bbf95c8a13'),
        ),
    ]
