# Generated by Django 4.0.2 on 2022-02-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/f064deed-b635-476b-9b7a-91a75e1d4a11'),
        ),
    ]
