# Generated by Django 4.0.2 on 2022-02-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/67247d1b-2b27-4a85-8853-69d921ede682'),
        ),
    ]
