# Generated by Django 4.0.2 on 2022-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appointment_customuser_doctor_id_alter_doctor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/894a850b-79a5-4f3b-829f-b6ee2cdc74cb'),
        ),
    ]
