# Generated by Django 4.0.2 on 2022-02-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appointment_customuser_doctor_id_alter_doctor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/086963d8-8a0d-4b89-87e6-ebb4973f8625'),
        ),
    ]
