# Generated by Django 4.0.2 on 2022-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/b07e889e-2ede-495a-8ded-8bed3cc9843a'),
        ),
    ]
