# Generated by Django 4.0.2 on 2022-02-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/10fe1a42-469e-419d-bce6-ecd6a52fa87b'),
        ),
    ]
