# Generated by Django 4.0.2 on 2022-02-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appointment_message_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/adbceafd-af63-498b-a2d9-7afdf66b4db0'),
        ),
    ]
