# Generated by Django 4.0.2 on 2022-02-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e750d7e6-6592-48ec-b74d-3f0f9aedf4f3'),
        ),
    ]
