# Generated by Django 4.0.2 on 2022-02-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/26b5774e-0fce-437f-9cdf-3ed3d0fa1527'),
        ),
    ]
