# Generated by Django 4.0.2 on 2022-02-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_doctor_image_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e313cce9-9441-451b-999c-75a48248d114'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
