# Generated by Django 4.0.2 on 2022-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/874a87cc-8f1e-4450-a050-fd78049ba83b'),
        ),
    ]
