# Generated by Django 4.0.2 on 2022-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/ad5356bd-cee2-40f1-9e1d-941c483d08e8'),
        ),
    ]
