# Generated by Django 4.0.2 on 2022-02-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/0f847c19-fb88-4b07-9f4b-54baf15ef5cd'),
        ),
    ]
