# Generated by Django 4.0.2 on 2022-02-18 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=16)),
                ('report', models.FileField(upload_to='uploads/% Y/% m/% d/')),
                ('phone', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='phone must be an egyptian phone number...', regex='^01[1|0|2|5][0-9]{8}$')], verbose_name='phone')),
                ('date_of_birth', models.DateField(null=True)),
                ('record_number', models.TextField()),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('guardian', models.CharField(max_length=20, null=True)),
                ('guardian_relation', models.CharField(choices=[('first degree', 'First Degree'), ('second degree', 'Second Degree')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/23454bfa-d5bb-41fe-8faa-e226eaa261e6'),
        ),
    ]
