# Generated by Django 4.0.2 on 2022-02-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guardian',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guardian_relation',
            field=models.CharField(choices=[('first degree', 'First Degree'), ('second degree', 'Second Degree')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/6d91be8f-a885-43ad-9262-09cb11e43198'),
        ),
    ]
