# Generated by Django 4.0.2 on 2022-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/2e7b91b6-3b72-41b0-8e29-759b8c6c76b5'),
        ),
    ]
