# Generated by Django 4.0.2 on 2022-02-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_guardian_customuser_guardian_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/1ff7296d-f903-4938-85d6-54344d85c8fe'),
        ),
    ]
