# Generated by Django 4.0.2 on 2022-02-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/9f823d98-abfb-40df-a336-0bf2f2c68a65'),
        ),
    ]
