# Generated by Django 4.0.2 on 2022-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/5f1e760b-3bfa-4e7a-b1b7-ad3989730834'),
        ),
    ]
