# Generated by Django 4.0.2 on 2022-02-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/9d3ecfc3-3047-4278-bd37-4db563e87bd0'),
        ),
    ]
