# Generated by Django 4.0.2 on 2022-02-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/4e1c97bc-0aaf-498e-8427-a195a075557e'),
        ),
    ]
