# Generated by Django 4.0.2 on 2022-02-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e1d7f255-9853-4b79-b47b-9f7815f242b3'),
        ),
    ]
