# Generated by Django 4.0.2 on 2022-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/bdf91776-beb0-41e4-b77e-26975c92c2eb'),
        ),
    ]
