# Generated by Django 4.0.2 on 2022-02-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/3c63a7b0-6ec5-4d07-8387-7691c66016c9'),
        ),
    ]
