# Generated by Django 4.0.2 on 2022-02-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e616b950-08ef-4b4e-8e34-52c69e25c38d'),
        ),
    ]
