# Generated by Django 4.0.2 on 2022-02-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/e9169de5-a90a-4806-b1b2-4af344342a83'),
        ),
    ]
